workload=site.ycsb.workloads.CoreWorkload
db=ASDClient

fieldcount=1
readallfields=true

insertpropotion=0
scanproportion=0
requestdistribution=uniform

measurementtype=timeseries

###Change only below

timeseries.granularity=5000

# quanto em quanto tempo aparecem os logs
status.interval=5

recordcount=10000

# duracao da experiencia
operationcount=3000

# quanto tempo estou disposto a esperar por uma operacao
timeout_millis=100000



